### ISSUE TITLE
File Not Found

### ISSUE THREAD

**Issue by chiragIOS** [WowzaMediaSystems/gocoder-sdk-samples-ios#1]
Hello Wowza team  WZBroadcastScaleMode is missing in your sample code

**Comment by chiragIOS** [comment]
ld: framework not found WowzaGoCoderSDK
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by manitou2k** [comment]
chiragIOS - Do you have a trial or production license to the GoCoder SDK?  These sample apps are for demonstrating the capabilities of the SDK and require a license to compile and run them. For more information on obtaining the SDK please look here: https://www.wowza.com/products/gocoder/sdk

**Comment by chiragIOS** [comment]
How to get trial License because i mailed to GoCoderSDK but i did not get any responce for trial License

**Comment by manitou2k** [comment]
Please email sdkteam@wowza.com and request a trial, if you do not get a response please let me know and I will follow up.
