### ISSUE TITLE
Unable to play local mp4 file

### ISSUE THREAD

**Issue by Alaakhodor** [WowzaMediaSystems/gocoder-sdk-samples-ios#16]
Hello,
I tried to play a local mp4 file using the samples, `WowzaGoCoderMP4PlayerSample` is just showing the record view and the video is not working. I even added my own mp4 to the target and modified the `assetURL` with the same result. Any guidance on how to play a local file?

**Comment by akeller** [comment]
Is this still an issue with the latest version? I will try to reproduce today.

**Comment by akeller** [comment]
Reproduced this, but was able to get it to work by adding my Wowza Streaming Engine information using the settings (cog/gear on the record view). Once you add that info, you are able to play the mp4. 

I'm going to go ahead and close this, but please reopen if you are still having issues on the latest version after adding your Wowza Streaming Engine or Wowza Streaming Cloud info in the settings.
