### ISSUE TITLE
How to broadcast VOD from one iOS device to other users iOS devices?

### ISSUE THREAD

**Issue by tapannathvani** [WowzaMediaSystems/gocoder-sdk-samples-ios#17]
Hello,

I installed Wowza service engine in my MacBook.. I added a video in Content folder and able to stream in my device but streaming is not working in multiple devices.. I checked on your sample app.. did the same configuration in both devices.. working only in 1 device? 

And is there any way to start broadcast (content folder video) from 1 iOS device and it should start streaming in multiple devices which has the same configuration?

**Comment by Wowza-Rose** [comment]
Hello @tapannathvani , I am wondering if this was resolved for you and I am sorry it was never responded to back In July when you posted it.  I would be curious to know what streaming protocol you used for playback. Did you enable the transcoder to transmux it to HLS which is what most devices are compatible with?

**Comment by akeller** [comment]
Closing this as stale.
