### ISSUE TITLE
Unkown type name 'WZBroadcastScaleMode'

### ISSUE THREAD

**Issue by symonty** [WowzaMediaSystems/gocoder-sdk-samples-ios#2]
Probably due to incorrect libraries included in the GIT?

@property (nonatomic, assign) WZBroadcastScaleMode broadcastScaleMode;

Line 69 SettingsViewModel.h

**Comment by bcyng** [comment]
i also get the same error

**Comment by lisa-wong** [comment]
Hello symonty and bcyng,
This issue sounds like you do not have either a trial or production GoCoder SDK license. These sample apps require a license to compile and run. Do you already have a license? If not, you can request a license from sdkteam@wowza.com.

**Comment by bcyng** [comment]
yes have a trial license. have entered the license key in the following line:
`static NSString *const SDKSampleAppLicenseKey =` in VideoPlayerViewController.m
this is a compile error not a license error...

the full error is below:
.../gocoder-sdk-samples-ios-master/SDKSampleApp.swift/SwiftSDKSampleApp-Bridging-Header.h:10:9: note: in file included from .../gocoder-sdk-samples-ios-master/SDKSampleApp.swift/SwiftSDKSampleApp-Bridging-Header.h:10:
#import "SettingsViewModel.h"
        ^
.../gocoder-sdk-samples-ios-master/shared/SettingsViewModel.h:69:31: error: unknown type name 'WZBroadcastScaleMode'
@property (nonatomic, assign) WZBroadcastScaleMode broadcastScaleMode;
                              ^
<unknown>:0: error: failed to import bridging header '.../gocoder-sdk-samples-ios-master/SDKSampleApp.swift/SwiftSDKSampleApp-Bridging-Header.h'

**Comment by symonty** [comment]
Yeah it is not a license issue looks like a feature declared not in the framework . WZBroadcastScaleMode is a new feature is it possibly not in the compiled framework , that is an older version?

--
Symonty 
info: http://symonty.org/sig/
+1-615-796-6689 [+1-N1L-SYMONTY]

**Comment by mleavy** [comment]
Sounds like you have an old version of the SDK. Please contact sdkteam@wowza.com for an update.

**Comment by ahmedb** [comment]
I get the same error on the  **master** branch. Tested 15 mins ago (7am PST, 6/22/16). I tested the Obj-C and Swift projects.

It does not resolve even when I comment the WZBroadcastScaleMode calls out of the sample code. It gives me a linker error: `ld: framework not found WowzaGoCoderSDK`

**Comment by ahmedb** [comment]
I was able to resolve the compiler errors I was having with the `WZBroadcastScaleMode` enum by replacing the sample framework in this project with the one from the SDK.

**Comment by symonty** [comment]
Thx, so the sample code is out of date as I thought.

**Comment by lisa-wong** [comment]
Thank you for the comments. We'll be updating the repo. Look for an update later today.

**Comment by lisa-wong** [comment]
@ahmedb @symonty The Framework has been updated. Thank you for the feedback.

**Comment by MittaKarthik** [comment]
I am using the sample app with Xcode 8.1 beta, still I am getting compile error framework not found. Why so...???

**Comment by mleavy** [comment]
Please take a look at the readme. It is readily viewable on the GitHub repo.
