### ISSUE TITLE
Can't archive project in xCode 11 (latest version)

### ISSUE THREAD

**Issue by kseniya-hydric** [WowzaMediaSystems/gocoder-sdk-samples-ios#20]
I'm trying to make a build with GoCoder framework embedded in my project but I get an error : "IPA processing failed". Did some searching and its to do with the framework using i386\x86_64 architectures. I also tried to archive your demo app and the same happens.
Using xCode 11.2.1.

<img width="738" alt="Screen Shot 2019-12-03 at 8 29 49 am" src="https://user-images.githubusercontent.com/15661926/70003216-34a5df00-15ae-11ea-99ff-9d140c9892c3.png">

**Comment by akeller** [comment]
Take a look at the answers to this post - https://stackoverflow.com/questions/42641806/check-and-remove-unsupported-architecture-x86-64-i386-in-ipa-archive
