### ISSUE TITLE
ld: framework not found WowzaGoCoderSDK

### ISSUE THREAD

**Issue by ahmedb** [WowzaMediaSystems/gocoder-sdk-samples-ios#3]
I can not get the sample projects from the **master** branch to compile on my device. It complains that the WZBroadcastScaleMode class is missing and when I comment it out, I get : 

`ld: framework not found WowzaGoCoderSDK`

Tested both SwiftSDKSampleApp and SDKSampleApp projects. Attempting to run project on an iPhone 6  running iOS 9.3.2 .

**Comment by ScottKell** [comment]
You need to get the SDK to compile and link the app.  See the readme:

Wowza GoCoder SDK. To get a copy of the SDK, send an email message to the Wowza SDK Team.

Regards,

Scott
