### ISSUE TITLE
Update headers in sample framework

### ISSUE THREAD

**Issue by ahmedb** [WowzaMediaSystems/gocoder-sdk-samples-ios#4]
I was able to resolve the compiler errors I was having with the `WZBroadcastScaleMode` enum by replacing the sample framework in this project with the one from the SDK.

Please update the headers for the sample framework in Git or remove the framework and make it more clear that you should place the SDK's framework file in the root directory of the project.

**Comment by mleavy** [comment]
The headers in WowzaGoCoderSDK.framework were out of date; they've been updated.
