### ISSUE TITLE
add CFilter for CVImageBufferRef in Gocoder SDK ios not effect?

### ISSUE THREAD

**Issue by dungdt9x** [WowzaMediaSystems/gocoder-sdk-samples-ios#5]
Hi guys, i try to use this code to add CIFilter for imageBuffer. But when i run in device, i dont see any change and dont see effect for camera also When i debug i can see frameImage is an image with gray color. Please help me 
- (void) videoFrameWasCaptured:(nonnull CVImageBufferRef)imageBuffer framePresentationTime:(CMTime)framePresentationTime frameDuration:(CMTime)frameDuration {
    if (self.goCoder.isStreaming) {
        
        if (self.blackAndWhiteVideoEffect) {
            // convert frame to b/w using CoreImage tonal filter
            CIImage *frameImage = [[CIImage alloc] initWithCVImageBuffer:imageBuffer];
            CIFilter *grayFilter = [CIFilter filterWithName:@"CIPhotoEffectTonal"];
            [grayFilter setValue:frameImage forKeyPath:@"inputImage"];
            frameImage = [grayFilter outputImage];

            CIContext * context = [CIContext contextWithOptions:nil];
            [context render:frameImage toCVPixelBuffer:imageBuffer];
        }
        
    }
}

**Comment by mleavy** [comment]
That only affects the video stream, not the preview.
