### ISSUE TITLE
strip-frameworks.sh files missing inside the WowzaGoCoderSDK.framework

### ISSUE THREAD

**Issue by tobitech** [WowzaMediaSystems/gocoder-sdk-samples-ios#6]
I've archived my iOS app with WowzaGoCoderSDK.framework but I'm getting errors for unsupported architecture. I've added the script line of code bash 
`"${BUILT_PRODUCTS_DIR}/${FRAMEWORKS_FOLDER_PATH}/WowzaGoCoderSDK.framework/strip-frameworks.sh"`

when I check the log it shows "No such file or directory"

**Comment by andyjriley** [comment]
This fix has been added since original posting. Issue can be closed.

**Comment by akeller** [comment]
Closing per above comment. Thanks!
