### ISSUE TITLE
Demo is not working 

### ISSUE THREAD

**Issue by girnarios** [WowzaMediaSystems/gocoder-sdk-samples-ios#7]
**clang: error: linker command failed with exit code 1 (use -v to see invocation)**

I have used your old **WowzaGoCoderSDK.framework** that is working fine in my demo. But I have replace this with your current version framework that giving linker error and not showing any file reference.
[Xcode Image URL](https://pasteboard.co/6UUpxrKj2.png)

**Comment by codexprojects** [comment]
Hello @girnarios 
You first need to create a free trial license key through [this url.](https://www.wowza.com/products/gocoder/sdk/trial)
After that you can download the working project from the link inside the e-mail.

**Comment by andyjriley** [comment]
@codexprojects is correct that you need a key to initiate. However your issue is related to a linker issue which has been fixed in current project. To fix with current setup add the WowzaGoCoderSDK.framework to embedded binaries within the target.

**Comment by akeller** [comment]
Closing this per last comment.
