### ISSUE TITLE
WZPlayer header not in WowzaGoCoderSDK

### ISSUE THREAD

**Issue by jsonfellin** [WowzaMediaSystems/gocoder-sdk-samples-ios#9]
I'm trying to display the Wowza stream and saw WZPlayer in the docs. It looks like an instance of this should be used but I don't see the header in the framework, am I missing something?

**Comment by akeller** [comment]
This header is available in the framework, please update to the latest version. Example of how to use it is in the WOWZPlayerViewController.

I know this is almost 2 years old at this point, but I need closure even if you have already moved on. :)
